// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiwrbdwqiqjmqqcjrvdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpd3JiZHdxaXFqbXFxY2pydmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTI0ODEsImV4cCI6MjA3MTM2ODQ4MX0.eq_5yMPdBtcgb9p3rFDsf3GbkAbbsUBuKFLgy2iVPqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});